# Generated by Django 4.0.4 on 2023-02-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userform_options_alter_userform_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userform',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userform',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userform',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='user_permissions',
        ),
    ]
