# Generated by Django 4.0.4 on 2023-02-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userform_options_alter_userform_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='username',
        ),
    ]
