# Generated by Django 4.0.4 on 2023-02-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_userform_email_remove_userform_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
