# Generated by Django 4.0.4 on 2023-03-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_gender_profile_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='music',
            new_name='musician',
        ),
    ]
