# Generated by Django 4.0.4 on 2023-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_song_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
