# Generated by Django 4.0.4 on 2023-04-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_song_emotion_song_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='musician',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
