# Generated by Django 4.0.4 on 2023-04-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_song_musician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='artist',
        ),
    ]
